name = "P4estTypes"
uuid = "f636fe8e-398d-42a9-9d15-dd2c0670d30f"
authors = ["Lucas C Wilcox <lucas@swirlee.com>"]
version = "0.1.0"

[deps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
P4est = "7d669430-f675-4ae7-b43e-fab78ec5a902"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
MPI = "0.19"
P4est = "0.3"
RecipesBase = "1"
julia = "1.6"
